### ISSUE TITLE
Refactor: Remove Tango SDK samples code + scenes

### ISSUE THREAD

**Issue by bertt** [bertt/tango#29]

**Comment by bertt** [comment]
also remove 'Example' with 'kanweg_GameControlPanel' and 'kanweg_LearningToggle'

**Comment by aiunderstand** [comment]
Agree, but mind you: gamecontrol panel and learningToggle are still integrated in some scripts so these need to be modded.

**Comment by bertt** [comment]
'kanweg_GameControlPanel' and 'kanweg_LearningToggle' are removed

**Comment by aiunderstand** [comment]
done
