### ISSUE TITLE
Question refactor: GameManager.Modi 

### ISSUE THREAD

**Issue by bertt** [bertt/tango#32]
There is an enumeration for the modi of app:

```
    public enum Modi {
        idle,
        isRecording,
        isNotRecording,
        isNavigating,
        isNotNavigating
    }
```

Question: can we remove IsNotRecording and isNotNavigating? Seems to me a duplicate (well inverse) of isRecording and IsNavigating

**Comment by aiunderstand** [comment]
Yes this part can be improved to three unique disjoint states.

**Comment by bertt** [comment]
removed isNotRecording, isNotNavigating

**Comment by bertt** [comment]
test: works okay
