### ISSUE TITLE
Where is the Adf file?

### ISSUE THREAD

**Issue by bertt** [bertt/tango#5]
Tried again to find the ADF files on the device, but no luck so far. Where are they stored exactly (external storage?) Can I see the files in a file explorer?
Related question: How to get to the bytes of current selected ADF? Tried '               areaDescription.ExportToFile("/storage/emulated/0/Download/test.pam");' but no file seems to be exported.

**Comment by bertt** [comment]
There is a Tango config property (TangoConfig.KeyStringDatasetsPath) thats set to '/data/data/com.google.tango/files/datasets/'

Hwoever, in adb there is a permission issue going to this directory

**Comment by bertt** [comment]
some adb hacking: must be something like '/data/data/com.google.tango/files/Tango/ADFs'

**Comment by bertt** [comment]
Testing getting acces to the adf using the 'ExportToFile' method, but no luck...

SAmple code:

```
$ var p= Application.persistentDataPath;
$ var res = mostRecent.ExportToFile(p + "/test.pam");
```

but /storage/emulated/0/Android/data/com.bertt.arealearning/files remains empty :-(

**Comment by aiunderstand** [comment]
Possibly helpful reads: 

- example of sending adf to client/server https://github.com/googlearchive/tango-examples-unity/blob/master/TangoWithMultiplayer/Assets/Scripts/MultiplayerCubeStackerUIController.cs
- getting a list of locallly available adf's https://github.com/googlearchive/tango-examples-unity/blob/master/TangoWithMultiplayer/Assets/Scripts/AreaDescriptionPickerUIController.cs
- have a responsive ui while saving big adf file https://stackoverflow.com/questions/45841171/areadescription-savecurrent-freezes-unitys-update-loop-despite-new-thread

**Comment by bertt** [comment]
got the export working by having a directory instead of a file in the .ExportToFile method. 
A file is created with the ADF Guid as name.
